version: "3"

services:
  api:
    build: /api/.
    container_name: api
    ports:
      - 8080:8080
  db:
    build: /db/.
    container_name: db
    ports:
      - 5432:5432
  web:
    build: /web/.
    container_name: web
    ports:
      - 80:80